package com.iflow.api.core.graphql;

/**
 * GraphQL 自动连线工厂
 * 
 * 引用：REQ-F1-003（动态 Schema 生成）
 */
public class AutoApiWiringFactory {

    /**
     * 检查是否为自动生成的字段
     */
    public boolean isAutoGeneratedField(String fieldName) {
        // 排除标准查询和变更字段
        if (fieldName.endsWith("List") || 
            fieldName.endsWith("ById") ||
            fieldName.startsWith("create") ||
            fieldName.startsWith("update") ||
            fieldName.startsWith("delete")) {
            return false;
        }
        return true;
    }
}
