-- 数据源配置表
CREATE TABLE IF NOT EXISTS `api_datasource_config` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `name` varchar(100) NOT NULL COMMENT '数据源名称',
    `type` varchar(50) NOT NULL COMMENT '数据源类型: mysql/postgresql/oracle/sqlserver',
    `host` varchar(255) NOT NULL COMMENT '主机地址',
    `port` int NOT NULL COMMENT '端口号',
    `database_name` varchar(100) NOT NULL COMMENT '数据库名称',
    `schema_name` varchar(100) DEFAULT NULL COMMENT '模式名称(PostgreSQL)',
    `username` varchar(100) NOT NULL COMMENT '用户名',
    `password` varchar(255) NOT NULL COMMENT '密码',
    `connection_params` varchar(500) DEFAULT NULL COMMENT '连接参数',
    `pool_config` varchar(1000) DEFAULT NULL COMMENT '连接池配置',
    `status` tinyint DEFAULT 1 COMMENT '状态: 0-禁用 1-启用',
    `is_primary` tinyint DEFAULT 0 COMMENT '是否主数据源: 0-否 1-是',
    `remark` varchar(500) DEFAULT NULL COMMENT '备注',
    `created_by` varchar(100) DEFAULT NULL COMMENT '创建人',
    `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_by` varchar(100) DEFAULT NULL COMMENT '更新人',
    `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` tinyint DEFAULT 0 COMMENT '删除标记: 0-未删除 1-已删除',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_name` (`name`),
    KEY `idx_type` (`type`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='数据源配置表';

-- 表选择配置表
CREATE TABLE IF NOT EXISTS `api_table_selection` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `datasource_id` bigint NOT NULL COMMENT '数据源配置ID',
    `table_name` varchar(100) NOT NULL COMMENT '表名',
    `table_comment` varchar(500) DEFAULT NULL COMMENT '表备注/描述',
    `selected` tinyint NOT NULL COMMENT '是否选择生成API: 0-未选中 1-选中',
    `generate_mode` varchar(20) DEFAULT 'auto' COMMENT '生成模式: auto-自动 manual-手动',
    `api_prefix` varchar(100) DEFAULT NULL COMMENT 'API路径前缀',
    `skip_reason` varchar(50) DEFAULT NULL COMMENT '跳过原因: already_exists-已存在API filtered-正则过滤 manual-手动取消 error-错误',
    `skip_reason_detail` varchar(500) DEFAULT NULL COMMENT '跳过说明',
    `include_columns` text COMMENT '包含字段列表(JSON数组)',
    `exclude_columns` text COMMENT '排除字段列表(JSON数组)',
    `custom_rules` text COMMENT '自定义API规则(JSON)',
    `priority` int DEFAULT 0 COMMENT '优先级(数字越小优先级越高)',
    `status` tinyint DEFAULT 1 COMMENT '状态: 0-草稿 1-已发布',
    `created_by` varchar(100) DEFAULT NULL COMMENT '创建人',
    `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_by` varchar(100) DEFAULT NULL COMMENT '更新人',
    `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` tinyint DEFAULT 0 COMMENT '删除标记: 0-未删除 1-已删除',
    PRIMARY KEY (`id`),
    KEY `idx_datasource_id` (`datasource_id`),
    KEY `idx_table_name` (`table_name`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='表选择配置表';

-- API生成状态表
CREATE TABLE IF NOT EXISTS `api_generation_status` (
    `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `api_path` varchar(200) NOT NULL COMMENT 'API路径',
    `generate_time` datetime DEFAULT NULL COMMENT '生成时间',
    `datasource_id` bigint NOT NULL COMMENT '数据源配置ID',
    `table_name` varchar(100) NOT NULL COMMENT '表名',
    `status` varchar(20) NOT NULL COMMENT '生成状态: pending-待生成 generating-生成中 generated-已生成 skipped-已跳过 error-错误 removed-已移除',
    `rest_api_path` varchar(200) DEFAULT NULL COMMENT 'REST API路径',
    `rest_api_registered` tinyint DEFAULT 0 COMMENT 'REST API是否已注册',
    `graphql_type` varchar(100) DEFAULT NULL COMMENT 'GraphQL Type名称',
    `graphql_registered` tinyint DEFAULT 0 COMMENT 'GraphQL Schema是否已注册',
    `error_message` text COMMENT '错误消息',
    `error_stack` text COMMENT '错误堆栈',
    `generated_at` datetime DEFAULT NULL COMMENT '生成时间',
    `last_refreshed_at` datetime DEFAULT NULL COMMENT '最后刷新时间',
    `generation_duration` bigint DEFAULT NULL COMMENT '生成耗时(毫秒)',
    `api_version` int DEFAULT 1 COMMENT 'API版本号',
    `metadata_version` bigint DEFAULT 1 COMMENT '元数据版本号',
    `created_at` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_api_path` (`api_path`),
    KEY `idx_datasource_id` (`datasource_id`),
    KEY `idx_table_name` (`table_name`),
    KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='API生成状态表';